import createClient, { type ClientOptions } from 'openapi-fetch';

export type { PathsWithMethod, ClientOptions } from 'openapi-fetch';

export interface ApiClientOptions extends ClientOptions {
  /** Base URL of the API. Typically from PUBLIC_API_BASE_URL env var. */
  baseUrl: string;
}

/**
 * Create a type-safe API client from an OpenAPI schema.
 *
 * Usage:
 *   import type { paths } from '$lib/api/schema.js'; // generated by openapi-typescript
 *   export const api = createApiClient<paths>({ baseUrl: PUBLIC_API_BASE_URL });
 *
 *   // In a load function:
 *   const { data, error } = await api.GET('/items/{id}', {
 *     params: { path: { id } },
 *     fetch, // forward SvelteKit's fetch for SSR cookie/dedup support
 *   });
 */
export function createApiClient<Paths extends Record<string, Record<string, unknown>>>(
  options: ApiClientOptions,
) {
  return createClient<Paths>(options);
}

export type ApiClient<Paths extends Record<string, Record<string, unknown>>> = ReturnType<
  typeof createApiClient<Paths>
>;
