// openapi-typescript codegen wrapper with sveltesentio defaults. Generates a
// typed `paths` module from an OpenAPI 3.x spec so `createClient<paths>` is
// fully typed. openapi-typescript is an OPTIONAL peer dep (build-time only) —
// it is injected (`deps`) so this stays unit-testable without a real spec file.
import type { OpenAPI3, OpenAPITSOptions } from 'openapi-typescript';

/** Subset of openapi-typescript's surface this wrapper needs; injectable for tests. */
export interface CodegenDeps {
	/** openapi-typescript default export: spec → TypeScript AST nodes. */
	openapiTS: (
		source: string | URL | OpenAPI3 | Buffer,
		options?: OpenAPITSOptions,
	) => Promise<readonly unknown[]>;
	/** openapi-typescript `astToString`: AST nodes → source text. */
	astToString: (ast: readonly unknown[]) => string;
}

export interface GenerateTypesOptions {
	/** Spec source: a path, URL, or already-parsed OpenAPI document. */
	source: string | URL | OpenAPI3;
	/** Forwarded to openapi-typescript. sveltesentio defaults are merged under these. */
	openapiTSOptions?: OpenAPITSOptions;
	/** Override the file header banner; pass `false` to omit it. */
	banner?: string | false;
}

/** Header prepended to generated files so they read as machine-output, not hand-edits. */
export const GENERATED_BANNER =
	'// Generated by @sveltesentio/api codegen (openapi-typescript). Do not edit by hand.\n';

// sveltesentio defaults: alphabetise members for stable diffs. Caller options win.
const DEFAULT_OPTIONS: OpenAPITSOptions = {
	alphabetize: true,
};

/**
 * Generate a typed `paths` module from an OpenAPI 3.x spec, as a string.
 *
 * ```ts
 * import openapiTS, { astToString } from 'openapi-typescript';
 * const dts = await generateTypes({ openapiTS, astToString }, { source: './openapi.yaml' });
 * ```
 */
export async function generateTypes(
	deps: CodegenDeps,
	options: GenerateTypesOptions,
): Promise<string> {
	const { source, openapiTSOptions, banner } = options;
	const ast = await deps.openapiTS(normalizeSource(source), {
		...DEFAULT_OPTIONS,
		...openapiTSOptions,
	});
	const body = deps.astToString(ast);
	if (banner === false) return ensureTrailingNewline(body);
	return (banner ?? GENERATED_BANNER) + ensureTrailingNewline(body);
}

// `OpenAPI3` documents pass straight through; path strings and URLs likewise.
// Centralised so the bin and the library agree on what a "source" is.
function normalizeSource(source: string | URL | OpenAPI3): string | URL | OpenAPI3 {
	return source;
}

function ensureTrailingNewline(text: string): string {
	return text.endsWith('\n') ? text : text + '\n';
}

export interface CodegenCliDeps extends CodegenDeps {
	/** Persist generated source. Injected so the bin is unit-testable. */
	writeFile: (path: string, contents: string) => Promise<void>;
	/** Sink for human-readable progress (defaults to `console.error` in the bin). */
	log?: (message: string) => void;
}

export interface CodegenCliResult {
	source: string;
	outFile: string;
	bytes: number;
}

/**
 * Resolve `[source, outFile]` from argv. Supports
 * `codegen <source> <outFile>` and `codegen <source> --out <outFile>`.
 */
export function parseCodegenArgs(argv: readonly string[]): {
	source: string;
	outFile: string;
} {
	const positionals: string[] = [];
	let outFlag: string | undefined;
	for (let i = 0; i < argv.length; i += 1) {
		const arg = argv[i];
		if (arg === undefined) continue;
		if (arg === '--out' || arg === '-o') {
			const next = argv[i + 1];
			if (next === undefined) throw new Error(`Missing value for ${arg}`);
			outFlag = next;
			i += 1;
			continue;
		}
		if (arg.startsWith('--out=')) {
			outFlag = arg.slice('--out='.length);
			continue;
		}
		positionals.push(arg);
	}
	const source = positionals[0];
	const outFile = outFlag ?? positionals[1];
	if (source === undefined || outFile === undefined) {
		throw new Error('Usage: sveltesentio-codegen <openapi-spec> <out.ts> [--out <out.ts>]');
	}
	return { source, outFile };
}

/**
 * Bin entrypoint: parse argv, generate the typed module, write it. Returns a
 * summary for testability; the thin `bin/` wrapper supplies real fs + openapi-typescript.
 */
export async function runCodegen(
	deps: CodegenCliDeps,
	argv: readonly string[],
): Promise<CodegenCliResult> {
	const { source, outFile } = parseCodegenArgs(argv);
	const contents = await generateTypes(deps, { source });
	await deps.writeFile(outFile, contents);
	deps.log?.(`Wrote ${outFile} (${contents.length} bytes) from ${source}`);
	return { source, outFile, bytes: contents.length };
}
